In [1]:
import numpy as np

a = np.array([1, 2, 3])

In [2]:
a * 3

array([3, 6, 9])

In [3]:
a + 2

array([3, 4, 5])

In [4]:
b = np.array([2, 2, 0])

In [5]:
a + b

array([3, 4, 3])

In [6]:
a / b

<ipython-input-6-d8e10abd5ab6>:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([0.5, 1. , inf])

In [7]:
a * b

array([2, 4, 0])

In [8]:
np.dot(a, b)

6

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10 ,2)

array([0, 2, 4, 6, 8])

In [11]:
np.linspace(0, 10, 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [12]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
c.shape

(2, 3)

In [14]:
np.sum(c)

21

In [15]:
np.sum(c, axis=1)

array([ 6, 15])

In [16]:
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
np.transpose(c)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
np.random.randn()

0.7183607340196909

In [20]:
np.random.rand()

0.9666974781912343

In [21]:
np.random.randn(2, 3)

array([[ 0.21251356,  0.14938988,  0.269752  ],
       [ 1.86152206, -1.84715553, -0.81734746]])

In [22]:
a

array([1, 2, 3])

In [23]:
a[0]

1

In [24]:
a[2]

3

In [25]:
a

array([1, 2, 3])

In [26]:
a[1] = 3

In [27]:
a

array([1, 3, 3])

In [28]:
d = np.array([0, 5, 2, 7, 1, 9])
d[1:5]

array([5, 2, 7, 1])

In [29]:
d[1:3]

array([5, 2])